# Generated by Django 4.2 on 2024-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
