# Generated by Django 4.2 on 2024-06-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_orders_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_order_id',
        ),
    ]
