# Generated by Django 4.2 on 2024-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_orders_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
